/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rebgy.xml.panels;

import com.rebgy.xml.clases.RowValues;

/**
 *
 * @author giovannyb
 */
public class RowPanel extends javax.swing.JPanel {
    
    public int pos;
    public RowValues row;
    
    public RowPanel() {
        initComponents();
    }
    public RowPanel(int name){
        initComponents();
        pos = name;
        nameRow.setText("Column " + name);
        serialCHBX.setSelected(false);
        notNullCHBX.setSelected(false);
        changeValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rowPNL = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        nameRow = new javax.swing.JLabel();
        rowName1 = new javax.swing.JTextField();
        dataTypeCMB = new javax.swing.JComboBox<>();
        serialCHBX = new javax.swing.JCheckBox();
        notNullCHBX = new javax.swing.JCheckBox();

        rowPNL.setLayout(new org.jdesktop.swingx.VerticalLayout());
        rowPNL.add(jSeparator1);

        nameRow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameRow.setText("Column");
        rowPNL.add(nameRow);

        rowName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rowName1FocusLost(evt);
            }
        });
        rowPNL.add(rowName1);

        dataTypeCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Type", "VARCHAR", "VARCHAR(50)", "VARCHAR(100)", "VARCHAR(150)", "INT" }));
        dataTypeCMB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dataTypeCMBItemStateChanged(evt);
            }
        });
        rowPNL.add(dataTypeCMB);

        serialCHBX.setText("Is Serial");
        serialCHBX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                serialCHBXItemStateChanged(evt);
            }
        });
        rowPNL.add(serialCHBX);

        notNullCHBX.setText("Not Null");
        notNullCHBX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                notNullCHBXItemStateChanged(evt);
            }
        });
        rowPNL.add(notNullCHBX);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rowPNL, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(rowPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rowName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rowName1FocusLost
        row.name.set(pos, rowName1.getText());
    }//GEN-LAST:event_rowName1FocusLost

    private void dataTypeCMBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dataTypeCMBItemStateChanged
        row.type.set(pos, String.valueOf(dataTypeCMB.getSelectedItem()));
    }//GEN-LAST:event_dataTypeCMBItemStateChanged

    private void serialCHBXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_serialCHBXItemStateChanged
        if(serialCHBX.isSelected())
            row.serial.set(pos, true);
        else
            row.serial.set(pos, false);
    }//GEN-LAST:event_serialCHBXItemStateChanged

    private void notNullCHBXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_notNullCHBXItemStateChanged
        if(notNullCHBX.isSelected())
            row.notNull.set(pos, true);
        else
            row.notNull.set(pos, false);
    }//GEN-LAST:event_notNullCHBXItemStateChanged
    public void changeValues(){
        if(notNullCHBX.isSelected())
            row.notNull.set(pos, true);
        else
            row.notNull.set(pos, false);
        if(serialCHBX.isSelected())
            row.serial.set(pos, true);
        else
            row.serial.set(pos, false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dataTypeCMB;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel nameRow;
    private javax.swing.JCheckBox notNullCHBX;
    private javax.swing.JTextField rowName1;
    private javax.swing.JPanel rowPNL;
    private javax.swing.JCheckBox serialCHBX;
    // End of variables declaration//GEN-END:variables

}
